# Generated by Django 4.2.1 on 2023-07-24 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='stripe_price_id',
            field=models.CharField(blank=True, default='abc', max_length=300, null=True),
        ),
    ]
