# Generated by Django 4.2.1 on 2024-06-11 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0002_alter_author_author_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'verbose_name': 'Assignment', 'verbose_name_plural': 'Assignments'},
        ),
        migrations.RenameField(
            model_name='video',
            old_name='description2',
            new_name='solution',
        ),
    ]
