# Generated by Django 4.2.1 on 2023-08-22 09:19

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0003_subscribedusers'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
