# Generated by Django 4.2.1 on 2023-08-22 10:09

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0005_alter_video_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='description2',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
