# Generated by Django 4.2.1 on 2023-08-25 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0006_video_description2'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='description_ru',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='course',
            name='title_ru',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
