# Generated by Django 4.2.1 on 2023-08-30 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0007_course_description_ru_course_title_ru'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=500)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='', max_length=2000)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school_app.course')),
            ],
        ),
    ]
