# Generated by Django 4.2.1 on 2023-08-30 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0009_rename_author_comment_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='review_title',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
