# Generated by Django 4.2.1 on 2023-08-31 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0013_comment_video_lecture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment_video_lecture',
            old_name='courses',
            new_name='videos',
        ),
    ]
