# Generated by Django 4.2.1 on 2023-08-31 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0014_rename_courses_comment_video_lecture_videos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment_video_lecture',
            name='videos',
        ),
        migrations.AddField(
            model_name='comment_video_lecture',
            name='lesson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school_app.lesson'),
        ),
    ]
