# Generated by Django 4.2.1 on 2023-08-31 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0015_remove_comment_video_lecture_videos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment_video_lecture',
            name='lesson',
        ),
        migrations.AddField(
            model_name='comment_video_lecture',
            name='videos',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school_app.video'),
        ),
    ]
