# Generated by Django 4.2.1 on 2024-04-22 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0016_remove_comment_video_lecture_lesson_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=100, null=True)),
                ('description', models.CharField(max_length=900, null=True)),
                ('image', models.ImageField(null=True, upload_to='Media/post_image')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school_app.author')),
            ],
        ),
    ]
