# Generated by Django 4.2.1 on 2024-06-06 11:16

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0018_blogpost_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='code',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
